### ISSUE TITLE
details of area coverage

### ISSUE THREAD

**Issue by goatslacker** [coveraje/coveraje#14]
I'd like details.

Line 27, false conditional wasn't covered, etc...

**Comment by WolfgangKluge** [comment]
As a list (like the errors/warnings in jshint)?
Should be no problem.

**Comment by goatslacker** [comment]
Yes very similar

**Comment by WolfgangKluge** [comment]
Now there is a (somewhat poor but expandable) ability to create reports.
`instance.report(format, options)`

where `format` can be a string (currently, there's only the "default"-format implemented, see /lib/report/default.js) or an object.
If it's an object, it should look like this

``` javascript
{
    format: {
        header: function (data, options),
        file: {
            header: function (data, filename, file, options),
            data: {
                visits: function (data, filename, file, options, isCovered) {},
                branches: function (data, filename, file, options, isCovered) {}
            },
            header: function (data, filename, file, options)
        },
        footer: function (data, options)
    },
    result: function (options) {} // called to get the result
}
```

**Comment by WolfgangKluge** [comment]
Is it sufficient?

**Comment by goatslacker** [comment]
LGTM for now. This issue can be closed.
