### ISSUE TITLE
Feature request: Support Mocha

### ISSUE THREAD

**Issue by goloroden** [coveraje/coveraje#16]
(The title already says it all)

**Comment by WolfgangKluge** [comment]
It's the next point on my list - support more TDD frameworks ;)
Do you have a project with which I can test it (real life) - except mocha itself.

**Comment by WolfgangKluge** [comment]
I added mocha support now. See examples/mocha_coveraje for an working example (you can see coverage results for mocha with it).
There are some known (and propably one or two unknown *g*) problems, but I think it's OK for the most tests now...

I'm waiting for https://github.com/visionmedia/mocha/issues/265

**Comment by WolfgangKluge** [comment]
Close this, since theres now a basic support for mocha...
