### ISSUE TITLE
beautify: true doesn't really beautify

### ISSUE THREAD

**Issue by goatslacker** [coveraje/coveraje#17]
I think you're overriding the user's option in lib/core.js

Sample code:

`foo.js`

```
var
  b = 10,
  c = (
    20,
    function (x) { return x + 100},
    function () { return arguments[0]}
  );
 
a = b + c({x: 10}).x; 
```

`cover.js`

```
var fs = require('fs');
var code = fs.readFileSync('./foo.js').toString();
var coverage = require('coveraje').coveraje;

coverage.cover(code, function (context, instance) {
  console.log(instance.getCodes());
  return coverage.runHelper.createEmitter(function (event) {
    event.complete();
  });
}, { colorizeShell: false, beautify: true }, function (results) {
//  console.log(results);
  console.log('Done.');
});
```

**Comment by WolfgangKluge** [comment]
Hmmm, it works for me...
the output to the console is json, but `results['initial code'].code` is the uglify-beautified version of `foo.js` (e.g. `var b` is written in one line).
You can see the beautified version in your browser, if you use option `useServer: true`

**Comment by goatslacker** [comment]
I'm talking about the instrumented code actually.

This line seems to be the offender: https://github.com/coveraje/coveraje/blob/master/lib/core.js#L538

**Comment by WolfgangKluge** [comment]
Oh, ok.
Just curious, what do you want with the instrumented code (injected with many calls to "_cj$_runtime, etc...)

**Comment by goatslacker** [comment]
I don't really need it beautified (although it does help for debugging). I'm just nitpicking at an inconsistency which seems easy to fix. I'm taking the instrument code and re-parsing it and adding entrance/exit functions to augment the testing.

**Comment by WolfgangKluge** [comment]
Make sense (especially debug)..will fix it

**Comment by goatslacker** [comment]
Turns out I do need it, the parser dies with compressed code. I think that's my fault though...

**Comment by WolfgangKluge** [comment]
Which parser.. Can you give me an example of koala-t script that runs into that issue

**Comment by goatslacker** [comment]
It's actually this file: https://github.com/goatslacker/node-typedjs/blob/contracts-refactor/lib/instrument.js I'm using esprima to parse it.

I have a feeling it's this line: https://github.com/goatslacker/node-typedjs/blob/contracts-refactor/lib/instrument.js#L156

**Comment by WolfgangKluge** [comment]
where is it gone - i have a fix ;)
Edit: see https://github.com/goatslacker/node-typedjs/pull/3
Edit2: but the comments are stripped by uglifyjs... So I don't know if it's useful for your. Maybe I should change the parser to keep the comments, too

**Comment by goatslacker** [comment]
I reparse for the comments because I have to reparse anyways so it's no big deal :)

**Comment by WolfgangKluge** [comment]
I now use the option also on instrumented code...
