### ISSUE TITLE
Add a function that returns result totals

### ISSUE THREAD

**Issue by goatslacker** [coveraje/coveraje#8]
Pull request coming.

**Comment by WolfgangKluge** [comment]
you can see the results in batch mode (`useServer = false`)..

I'm working on ability to see coverage reports of multiple files - and there are many changes in the way the results are treated internally (so please wait for this feature before any pull request with many changes... it's coming soon)

**Comment by WolfgangKluge** [comment]
Ah, I see. "a function"... ;)

**Comment by goatslacker** [comment]
It's a small commit. It's actually already done in a branch. I'm just working on the names returned at this point:

https://github.com/goatslacker/coveraje/commit/13e3beab74f06626b6f360c588966eb7a5edb12c

Oh, I also need to refactor `node-coveraje.js` to use this function as well

**Comment by goatslacker** [comment]
I'll separate the refactor into a different commit so you can cherry pick what you like.

**Comment by WolfgangKluge** [comment]
Small commits are no problem... (hope so ;))

**Comment by WolfgangKluge** [comment]
Now in master branch...
